name: Deploy Angular to EC2

on:  
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
          
      - name: Build Angular app
        run: npm run build --prod

      - name: Setup SSH and Deploy using rsync
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ec2-user
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$EC2_SSH_KEY" > private_key.pem
          chmod 600 private_key.pem
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no -i private_key.pem" dist/logit/ $EC2_USER@$EC2_HOST:/var/www/html/
          rm -f private_key.pem