name: Release Automation

on:
  push:
    branches: [master]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - run: npm ci

      - name: Generate CHANGELOG
        run: npx conventional-changelog -p angular -i CHANGELOG.md -s

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update release artifacts [skip ci]"
          file_pattern: CHANGELOG.md